# Generated by Django 4.0 on 2022-01-01 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoslist',
            name='shared_owner',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
